server:
  port: 8000

spring:
  application:
    name: websocket-interface-server
  kafka:
    bootstrap-servers: ${spring.environment.local.host}:9092
    consumer:
      group-id: websocket-interface-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  environment:
    local:
      host: 192.168.0.2
      port: 6379
      password: ssafy
    stage:
      host: 52.79.223.21
      port: 6379
      password: ssafy

    production:
      host: i6c209.p.ssafy.io
      port: 6379
      password: $$jae923009$
    sub:
      host: 13.125.149.219
      port: 6379
      password: ssafy

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      springframework: INFO
      kurento: INFO

