server:
  port: 8090


spring:
  application:
    name: chatservice

eureka:
  client:
    register-with-eureka: true
    fatch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka