spring:
  application:
    name: gameservice
  kafka:
    bootstrap-servers: ${spring.environment.work.host}:9092

    consumer:
      group-id: game-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  environment:
    local:
      host: 192.168.0.2
      port: 6379
    stage:
      host: 52.78.84.125
      port: 6379
      password: ssafy
    production:
      host: i6c209.p.ssafy.io
      port: 6379
      password: ssafy
    work:
      host: 52.79.223.21
      port: 6379
      password: ssafy

server:
  port: 8082
#eureka:
#  client:
#    register-with-eureka: true
#    fatch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
